<?php
/*
    require_once("../../../../wp-load.php");

    $coleccion_slugs = json_decode(listado_slugs(), true);


    $mi_query = array(
        'numberposts' => -1,
        'post_type' => 'product'
    );

    $resultados_query = get_posts($mi_query);

    foreach ($resultados_query as $producto){
        $slug_producto = $producto->post_name;

        foreach($coleccion_slugs as $slug_fila_key => $slug_fila_value){
            foreach($slug_fila_value as $slug_key => $slug_value){
                if ($slug_value == $slug_producto){
                    //Producto encontrado, hay que hacerlo privado.
                    
                    $update_post = array(
                        'post_type' => 'product',
                        'ID' => $producto->ID,
                        'post_status' => 'private'
                    );
                    echo "<br>Producto para marcar como privado: ".$slug_value;
                    wp_update_post($update_post);
                    echo " --> HECHO ";

                    break;
                }
            }
        }
    }


    function listado_slugs(){
        $coleccion = '
        [
            {
            "nike-sb-dunk-low-grateful-dead-orange":"nike-sb-dunk-low-grateful-dead-orange"
            },
            {
            "nike-sb-dunk-low-instant-skateboards":"nike-sb-dunk-low-instant-skateboards"
            },
            {
            "nike-air-force-x-stussy":"nike-air-force-x-stussy"
            },
            {
            "nike-dunk-sb-high-white-ice":"nike-dunk-sb-high-white-ice"
            },
            {
            "air-jordan-1-low-court-purple-black":"air-jordan-1-low-court-purple-black"
            },
            {
            "nike-dunk-sb-high-dr-seuss":"nike-dunk-sb-high-dr-seuss"
            },
            {
            "nike-sb-dunk-high-kentucky":"nike-sb-dunk-high-kentucky"
            },
            {
            "jordan-1-mid-hyper-royal-gs":"jordan-1-mid-hyper-royal-gs"
            },
            {
            "jordan-1-mid-se-union-black-toe":"jordan-1-mid-se-union-black-toe"
            },
            {
            "jordan-1-low-gold-toe":"jordan-1-low-gold-toe"
            },
            {
            "jordan-1-mid-sisterhood":"jordan-1-mid-sisterhood"
            },
            {
            "jordan-1-mid-se-union-royal":"jordan-1-mid-se-union-royal"
            },
            {
            "jordan-1-mid-turf-orange":"jordan-1-mid-turf-orange"
            },
            {
            "jordan-1-mid-signal-blue":"jordan-1-mid-signal-blue"
            },
            {
            "jordan-1-mid-composition-notebook":"jordan-1-mid-composition-notebook"
            },
            {
            "jordan-1-retro-high-volt-gold":"jordan-1-retro-high-volt-gold"
            },
            {
            "jordan-1-mid-banned-2020":"jordan-1-mid-banned-2020"
            },
            {
            "jordan-1-mid-patent-black-white-gold":"jordan-1-mid-patent-black-white-gold"
            },
            {
            "jordan-1-mid-se-lakers":"jordan-1-mid-se-lakers"
            },
            {
            "jordan-1-mid-alternate-think-16":"jordan-1-mid-alternate-think-16"
            },
            {
            "jordan-1-mid-fearless-facetasm":"jordan-1-mid-fearless-facetasm"
            },
            {
            "jordan-1-mid-paintstroke":"jordan-1-mid-paintstroke"
            },
            {
            "jordan-11-low-pink-snakeskin":"jordan-11-low-pink-snakeskin"
            },
            {
            "nike-sb-dunk-low-x-supreme-mean-green":"nike-sb-dunk-low-x-supreme-mean-green"
            },
            {
            "nike-sb-dunk-low-x-supreme-black":"nike-sb-dunk-low-x-supreme-black"
            },
            {
            "nike-air-force-1-low-pixel-red":"nike-air-force-1-low-pixel-red"
            },
            {
            "nike-air-force-1-low-pixel-iridescent":"nike-air-force-1-low-pixel-iridescent"
            },
            {
            "nike-sb-dunk-high-invert-celtics":"nike-sb-dunk-high-invert-celtics"
            },
            {
            "nike-air-force-1-low-pixel-snake":"nike-air-force-1-low-pixel-snake"
            },
            {
            "jordan-1-mid-camo":"jordan-1-mid-camo"
            },
            {
            "jordan-13-chinese-new-year":"jordan-13-chinese-new-year"
            },
            {
            "jordan-11-low-university-blue":"jordan-11-low-university-blue"
            },
            {
            "air-force-shadow-pink-black":"air-force-shadow-pink-black"
            },
            {
            "jordan-1-rage-green":"jordan-1-rage-green"
            },
            {
            "jordan-retro-4-travis-scott-purple":"jordan-retro-4-travis-scott-purple"
            },
            {
            "nike-sb-dunk-low-heineken":"nike-sb-dunk-low-heineken"
            },
            {
            "nike-sb-dunk-low-grateful-dead-green":"nike-sb-dunk-low-grateful-dead-green"
            },
            {
            "jordan-1-low-reverse-bred":"jordan-1-low-reverse-bred"
            },
            {
            "nike-dunk-low-disrupt-photon-dust":"nike-dunk-low-disrupt-photon-dust"
            },
            {
            "nike-dunk-low-disrupt-beige":"nike-dunk-low-disrupt-beige"
            },
            {
            "nike-dunk-low-disrupt-red":"nike-dunk-low-disrupt-red"
            },
            {
            "nike-sb-dunk-low-6":"nike-sb-dunk-low-6"
            },
            {
            "jordan-1-black-cheetah-kid":"jordan-1-black-cheetah-kid"
            },
            {
            "nike-air-force-shadow-spruce-aura-kid":"nike-air-force-shadow-spruce-aura-kid"
            },
            {
            "nike-air-force-shadow-pale-ivory-kid":"nike-air-force-shadow-pale-ivory-kid"
            },
            {
            "nike-air-force-shadow-black-yellow-kid":"nike-air-force-shadow-black-yellow-kid"
            },
            {
            "jordan-1-mid-shattered-kid":"jordan-1-mid-shattered-kid"
            },
            {
            "nike-air-force-1-9":"nike-air-force-1-9"
            },
            {
            "converse-all-star-plataforma":"converse-all-star-plataforma"
            },
            {
            "nike-air-jordan-4-6":"nike-air-jordan-4-6"
            },
            {
            "air-force-low-ribbon-pack":"air-force-low-ribbon-pack"
            },
            {
            "jordan-1-rookie-of-the-year":"jordan-1-rookie-of-the-year"
            },
            {
            "off-white-gold-black-hoodie":"off-white-gold-black-hoodie"
            },
            {
            "jordan-1-mid-black-red-kid":"jordan-1-mid-black-red-kid"
            },
            {
            "jordan-1-mid-red-blue-kid":"jordan-1-mid-red-blue-kid"
            },
            {
            "jordan-1-retro-high-top-3":"jordan-1-retro-high-top-3"
            },
            {
            "nike-air-force-1-low-have-a-nike-day-white":"nike-air-force-1-low-have-a-nike-day-white"
            },
            {
            "jordan-retro-4-university-blue":"jordan-retro-4-university-blue"
            },
            {
            "jordan-1-low-all-star-2021":"jordan-1-low-all-star-2021"
            },
            {
            "nike-blazer-mid-77-vintage-white-beige":"nike-blazer-mid-77-vintage-white-beige"
            },
            {
            "nike-air-max-720":"nike-air-max-720"
            },
            {
            "nike-air-jordan-4-3":"nike-air-jordan-4-3"
            },
            {
            "jordan-1-retro-high-not-for-resale-2":"jordan-1-retro-high-not-for-resale-2"
            },
            {
            "jordan-11-concord-blue":"jordan-11-concord-blue"
            },
            {
            "nike-air-max-97-x-off-white-black":"nike-air-max-97-x-off-white-black"
            },
            {
            "jordan-1-new-love-kid":"jordan-1-new-love-kid"
            },
            {
            "nike-air-max-97-have-a-nike-day-tropical-blue":"nike-air-max-97-have-a-nike-day-tropical-blue"
            },
            {
            "nike-sb-dunk-low-white-pink":"nike-sb-dunk-low-white-pink"
            },
            {
            "jordan-4-motorsport":"jordan-4-motorsport"
            },
            {
            "nike-air-force-1-low-black-gum":"nike-air-force-1-low-black-gum"
            },
            {
            "nike-air-max-720-2":"nike-air-max-720-2"
            },
            {
            "adidas-yeezy-350-3":"adidas-yeezy-350-3"
            },
            {
            "nike-air-force-type-1-3":"nike-air-force-type-1-3"
            },
            {
            "jordan-3-retro-korea":"jordan-3-retro-korea"
            },
            {
            "jordan-1-mid-multicolor-kid":"jordan-1-mid-multicolor-kid"
            },
            {
            "jordan-1-mid-black-chile-red-white":"jordan-1-mid-black-chile-red-white"
            },
            {
            "nike-air-force-1-pixel-ghost-aqua":"nike-air-force-1-pixel-ghost-aqua"
            },
            {
            "nike-rubber-dunk-x-off-white-unc":"nike-rubber-dunk-x-off-white-unc"
            },
            {
            "gucci-slipers":"gucci-slipers"
            },
            {
            "jordan-11-playoff-retro-bred":"jordan-11-playoff-retro-bred"
            },
            {
            "jordan-1-mid-racer-blue":"jordan-1-mid-racer-blue"
            },
            {
            "nike-air-force-1-utility-2":"nike-air-force-1-utility-2"
            },
            {
            "nike-air-force-type-1":"nike-air-force-type-1"
            },
            {
            "nike-air-max-97-2":"nike-air-max-97-2"
            },
            {
            "nike-vapormax-plus-3":"nike-vapormax-plus-3"
            },
            {
            "converse-all-star-high-4":"converse-all-star-high-4"
            },
            {
            "nike-vapormax-plus-13":"nike-vapormax-plus-13"
            },
            {
            "nike-air-jordan-1-black-trooper-sequoia":"nike-air-jordan-1-black-trooper-sequoia"
            },
            {
            "nike-air-jordan-1-11":"nike-air-jordan-1-11"
            },
            {
            "jordan-1-retro-high-black-satin":"jordan-1-retro-high-black-satin"
            },
            {
            "nike-sage-socks-orange":"nike-sage-socks-orange"
            },
            {
            "nike-air-force-shadow-triple-white-kid":"nike-air-force-shadow-triple-white-kid"
            },
            {
            "nike-air-force-skeleton-black":"nike-air-force-skeleton-black"
            },
            {
            "nike-zoom-spiridon-x-stussy":"nike-zoom-spiridon-x-stussy"
            },
            {
            "jordan-1-mid-varsity-yellow":"jordan-1-mid-varsity-yellow"
            },
            {
            "jordan-1-mid-dia-de-los-muertos":"jordan-1-mid-dia-de-los-muertos"
            },
            {
            "jordan-1-low-court-purple-white":"jordan-1-low-court-purple-white"
            },
            {
            "nike-dunk-low-disrupt-black":"nike-dunk-low-disrupt-black"
            },
            {
            "jordan-1-retro-high-midnight-navy":"jordan-1-retro-high-midnight-navy"
            },
            {
            "nike-blazer-mid-77-vintage-white-black":"nike-blazer-mid-77-vintage-white-black"
            },
            {
            "nike-air-force-1-utility-brown":"nike-air-force-1-utility-brown"
            },
            {
            "nike-air-max-95-3":"nike-air-max-95-3"
            },
            {
            "converse-all-star-high-3":"converse-all-star-high-3"
            },
            {
            "nike-zoom-2k":"nike-zoom-2k"
            },
            {
            "nike-air-force-sage":"nike-air-force-sage"
            },
            {
            "nike-air-jordan-1-24":"nike-air-jordan-1-24"
            },
            {
            "nike-air-jordan-4-cactus-jack":"nike-air-jordan-4-cactus-jack"
            },
            {
            "jordan-1-retro-high-nc":"jordan-1-retro-high-nc"
            },
            {
            "jordan-1-retro-high-shadow":"jordan-1-retro-high-shadow"
            },
            {
            "jordan-4-retro-raptors-2018":"jordan-4-retro-raptors-2018"
            },
            {
            "nike-sage-socks-gum-pink":"nike-sage-socks-gum-pink"
            },
            {
            "nike-air-force-shadow-pastel-kid":"nike-air-force-shadow-pastel-kid"
            },
            {
            "jordan-1-mid-island-green":"jordan-1-mid-island-green"
            },
            {
            "nike-air-force-1-high":"nike-air-force-1-high"
            },
            {
            "nike-air-jordan-1-8":"nike-air-jordan-1-8"
            },
            {
            "nike-air-force-utility-yellow":"nike-air-force-utility-yellow"
            },
            {
            "jordan-retro-11-3":"jordan-retro-11-3"
            },
            {
            "nike-sb-dunk-low-4":"nike-sb-dunk-low-4"
            },
            {
            "jordan-3-retro-black-cement":"jordan-3-retro-black-cement"
            },
            {
            "jordan-1-retro-high-pass-the-torch":"jordan-1-retro-high-pass-the-torch"
            },
            {
            "nike-air-force-1-react-white-pure-platinum":"nike-air-force-1-react-white-pure-platinum"
            },
            {
            "nike-sb-dunk-high-vast-grey":"nike-sb-dunk-high-vast-grey"
            },
            {
            "jordan-1-retro-high-silver-toe":"jordan-1-retro-high-silver-toe"
            },
            {
            "nike-air-force-1-high-2":"nike-air-force-1-high-2"
            },
            {
            "nike-air-max-97-4":"nike-air-max-97-4"
            },
            {
            "nike-air-max-97-8":"nike-air-max-97-8"
            },
            {
            "nike-m2k-tekno-2":"nike-m2k-tekno-2"
            },
            {
            "nike-air-max-270-7":"nike-air-max-270-7"
            },
            {
            "nike-air-max-270-8":"nike-air-max-270-8"
            },
            {
            "nike-air-jordan-1-sneakers-nike-air-jordan-1-red-rush-blue-university":"nike-air-jordan-1-sneakers-nike-air-jordan-1-red-rush-blue-university"
            },
            {
            "nike-air-jordan-1-7":"nike-air-jordan-1-7"
            },
            {
            "nike-airforce-shadow-black":"nike-airforce-shadow-black"
            },
            {
            "nike-air-jordan-1-guava-ice":"nike-air-jordan-1-guava-ice"
            },
            {
            "nike-sb-dunk-low-5":"nike-sb-dunk-low-5"
            },
            {
            "air-force-1-low-ribbon-pack-4":"air-force-1-low-ribbon-pack-4"
            },
            {
            "nike-air-force-1-just-do-it-2":"nike-air-force-1-just-do-it-2"
            },
            {
            "nike-air-force-shadow-7":"nike-air-force-shadow-7"
            },
            {
            "jordan-1-retro-high-not-for-resale":"jordan-1-retro-high-not-for-resale"
            },
            {
            "jordan-1-retro-high-4":"jordan-1-retro-high-4"
            },
            {
            "nike-airforce-shadow-pink-foam":"nike-airforce-shadow-pink-foam"
            },
            {
            "nike-shox-tl":"nike-shox-tl"
            },
            {
            "nike-vapormax-plus-11":"nike-vapormax-plus-11"
            },
            {
            "nike-air-force-shadow-5":"nike-air-force-shadow-5"
            },
            {
            "nike-air-force-1-10":"nike-air-force-1-10"
            },
            {
            "nike-vapormax-x-off-white":"nike-vapormax-x-off-white"
            },
            {
            "nike-tn":"nike-tn"
            },
            {
            "nike-tn-2":"nike-tn-2"
            },
            {
            "nike-air-jordan-1-25":"nike-air-jordan-1-25"
            },
            {
            "nike-sb-dunk-low-2":"nike-sb-dunk-low-2"
            },
            {
            "nike-sb-dunk-low-orange-label-white-gum":"nike-sb-dunk-low-orange-label-white-gum"
            },
            {
            "nike-air-max-270":"nike-air-max-270"
            },
            {
            "nike-air-max-270-3":"nike-air-max-270-3"
            },
            {
            "nike-air-force-shadow-10":"nike-air-force-shadow-10"
            },
            {
            "nike-vapormax-plus-9":"nike-vapormax-plus-9"
            },
            {
            "converse-all-star":"converse-all-star"
            },
            {
            "airforce-x-off-white":"airforce-x-off-white"
            }
         ]
        ';
        return $coleccion;
    }
*/
?>